include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
  enable-experiment:
    - records

linter:
  rules:
    - comment_references
    - test_types_in_equals
    - throw_in_finally